name: Improvement
description: Improve something
title: "[Improvement]: "
labels: [todo, Improvement]
body:
  - type: textarea
    attributes:
      label: Content
    validations:
      required: false
