name: Build to Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set-up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Check jdk version
        run: java --version


      - name: Build with gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Rename Artifact
        run: mv ./build/libs/PandaForceItemBattle-1.0.jar ./ForceItemBattle.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: ./ForceItemBattle.jar

      - name: Generate Build Info
        id: var
        run: |
            echo "full_sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
            echo "short_sha=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: binary

      - name: Echo build sha256
        id: build_sha
        run: |
          sha256sum ForceItemBattle.jar > sha256.checksum
          echo "build_sha=$(cat sha256.checksum)" >> $GITHUB_OUTPUT
          cat sha256.checksum

      - name: Run latest-tag
        uses: EndBug/latest-tag@84c87607fcb948bcef069c9a27445e653113979f
        with:
          ref: latest

      - name: Latest Release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest [${{ needs.build_nightly.outputs.short_sha }}]
          tag_name: latest
          body: |
            **Automated build**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            Build SHA256:
            ```
            ${{ steps.build_sha.outputs.build_sha }}
            ```
            
            Full Commit Hash:
            ```
            ${{ needs.build_nightly.outputs.full_sha }}
            ```
          files: |
            ForceItemBattle.jar
